minc-leash: minc: Add --pivot option for chroot applications
Add --pivot option for the application which requires
chroot (e.g. sshd).
For the normal application, minc provide a container
in which cap_sys_chroot is dropped. However, some application
including sshd requires chroot for privilege separation.

diff --git a/libexec/minc-leash b/libexec/minc-leash
--- a/libexec/minc-leash
+++ b/libexec/minc-leash
@@ -25,7 +25,7 @@ if test ! -d "$RD" ; then
 fi
 shift 1
 
-if which capsh > /dev/null 2>&1; then
+if test $MINC_PIVOT -ne 1 && which capsh > /dev/null 2>&1; then
   :;: 'Drop cap_sys_chroot to prohibit chroot-breakout';:
   MINC_DROPCAPS="$MINC_DROPCAPS,cap_sys_chroot"
   :;: 'Check capsh --exec is supported';:
@@ -61,7 +61,12 @@ OPT=
 if [ -z "$MINC_DROPCAPS" -o "$MINC_USERSPEC" ]; then
   :;: 'If the rootfs is initramfs, we can not use pivot_root';:
   if mount | grep -q ^"rootfs on / " ; then
-    echo "Warning: Failed to drop cap_sys_chroot. chroot breakout is available"
+    if test $MINC_PIVOT -eq 1 ; then
+      echo "Error: pivot_root is not available because rootfs is initramfs"
+      exit 1
+    else
+      echo "Warning: Failed to drop cap_sys_chroot. chroot breakout is available"
+    fi
   else
     :;: 'To unmount all unused mountpoints, use pivot_root to change root';:
     cd $RD
